VP-7031: Refactor all inputs in catalog, category and item detail blades to register dynamically and render in va-metaform
VirtoCommerce/vc-module-catalog pull request #484
Opened 2021-02-22 10:35 UTC by eMazeika

2021-02-24 08:30 UTC, AliveMen commented
PR description needed.

2021-02-24 08:45 UTC, AliveMen reviewed
Code is perfect. Please add PR description and example of how to hide any field in jira task.

2021-02-24 12:05 UTC, Vectorfield4 requested changes
Please attach the Jira-task link to the description.

2021-02-25 07:52 UTC, Vectorfield4 approved these changes

2021-02-25 08:39 UTC, AliveMen approved these changes

2021-02-25 11:31 UTC, merged