PT-2258: Update Catalog module
VirtoCommerce/vc-module-catalog pull request #543
Opened 2021-09-07 12:27 UTC by aizhuli

## Description
Update Catalog module to implement Generic CRUD Services

## References
### QA-test:
### Jira-link: https://virtocommerce.atlassian.net/browse/PT-2258
### Artifact URL:

2021-09-09 06:22 UTC, eMazeika requested changes
check sonar comments as well

2021-09-09 06:22 UTC, eMazeika commented on src/VirtoCommerce.CatalogModule.BulkActions/VirtoCommerce.CatalogModule.BulkActions.csproj
> +        <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.18" />
current Platform references 
<PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" Version="3.1.13" />
and module can't reference higher version then Platform does. Sync them.

2021-09-09 06:22 UTC, eMazeika commented on tests/VirtoCommerce.CatalogModule.Tests/PropertyDictionaryItemTest.cs
> +            var productCrudService = new Mock<IItemService>().As<ICrudService<CatalogProduct>>();
rename to follow single naming style

2021-09-09 06:22 UTC, eMazeika commented on src/VirtoCommerce.CatalogModule.Web/VirtoCommerce.CatalogModule.Web.csproj
>          <PackageReference Include="VirtoCommerce.Platform.Security" Version="3.57.0" />
the same version of Platform should be referenced (3.62)

2021-09-09 06:22 UTC, eMazeika commented on src/VirtoCommerce.CatalogModule.Data/VirtoCommerce.CatalogModule.Data.csproj
>          <PackageReference Include="VirtoCommerce.Platform.Security" Version="3.57.0" />
sync versions

2021-09-09 06:22 UTC, eMazeika commented on src/VirtoCommerce.CatalogModule.Data/Services/CategoryService.cs
> +        private new readonly IEventPublisher _eventPublisher;
consider removing all "private new" and using inherited members

2021-09-09 06:22 UTC, eMazeika commented on src/VirtoCommerce.CatalogModule.Data/Services/ItemService.cs
> +        private new readonly IPlatformMemoryCache _platformMemoryCache;
consider removing all "private new" and using inherited members

2021-09-09 06:22 UTC, eMazeika commented on src/VirtoCommerce.CatalogModule.Data/Services/PropertyDictionaryItemService.cs
> +        private new readonly IPlatformMemoryCache _platformMemoryCache;
consider removing all "private new" and using inherited members

2021-09-10 13:19 UTC, ksavosteev commented on src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepository.cs
> +        public virtual async Task<IEnumerable<ItemEntity>> GetItemByIdsAsync(IEnumerable<string> itemIds, string responseGroup = null)
DISALLOWED: Changing the type of a member

2022-08-19 06:01 UTC, akak1977 commented
Closed for reason of priority PR:
https://github.com/VirtoCommerce/vc-module-catalog/pull/612

2022-08-19 06:01 UTC, closed without merging