PT-5570: Update catalog module popups
VirtoCommerce/vc-module-catalog pull request #576
Opened 2021-12-15 08:37 UTC by Pav-el

## Description

## References
### QA-test:
### Jira-link:
### Artifact URL:

2021-12-17 07:52 UTC, akak1977 approved these changes

2021-12-17 09:20 UTC, asvishnyakov requested changes

2021-12-17 11:49 UTC, Pav-el commented on src/VirtoCommerce.CatalogModule.Web/Scripts/dialogs/deletePropertyDictionaryItem-dialog.tpl.html
> +        <button class="modal-window__footer-button modal-window__footer-button--primary" ng-click="no()">{{ 'platform.commands.cancel' | translate }}</button>
Yep, thanks. Fixed.

2021-12-20 07:34 UTC, asvishnyakov approved these changes

2021-12-20 07:37 UTC, merged