Ensure that saved editorial reviews are not marked as inherited
VirtoCommerce/vc-module-catalog pull request #730
Opened 2024-05-08 10:44 UTC by j-mok

When I have a product variation that inherit reviews (descriptions) from the parent, these reviews are editable, but the edits won't get persisted in the database - they get silently dropped without a warning. This behavior is due to the fact that those edited inherited reviews are ignored when mapping `CatalogProduct` to `ItemService` - [there's a filter](https://github.com/VirtoCommerce/vc-module-catalog/blob/f55012d8b82928a681dc1b3d2ef01b44ff818beb/src/VirtoCommerce.CatalogModule.Data/Model/ItemEntity.cs#L356) on `EditorialReview.IsInherited` property.

This PR offers a small change in the UI code, that clears the `isInherited` flag on those editorial reviews that got saved, effectively promoting them to variation's own reviews. In effect, the user can now directly override inherited reviews in variants.

2024-05-08 11:03 UTC, OlegoO approved these changes

2024-05-09 09:13 UTC, artem-dudarev requested changes

2024-05-09 09:13 UTC, artem-dudarev commented on src/VirtoCommerce.CatalogModule.Web/Scripts/blades/editorialReview-detail.js
> +            blade.currentEntity.isInherited = false;
Please remove code duplication by calling the `saveChanges()` function, which is declared later in this file.

2024-05-09 09:13 UTC, artem-dudarev commented on src/VirtoCommerce.CatalogModule.Web/Scripts/blades/editorialReview-detail.js
> +            blade.currentEntity.isInherited = false;
This flag should be changed before `angular.copy()`. Now it doesn't have any effect.

2024-05-10 13:17 UTC, artem-dudarev approved these changes

2024-05-13 12:49 UTC, merged