VCST-2223: Add Product Configuration functionality
VirtoCommerce/vc-module-catalog pull request #758
Opened 2024-11-21 16:31 UTC by Ljutyj

## Description
feat: Add Product Configuration functionality, fixed localization,

## References
### QA-test:
### Jira-link:
### Artifact URL:

2024-11-22 11:23 UTC, ksavosteev requested changes

2024-11-22 11:23 UTC, ksavosteev commented on src/VirtoCommerce.CatalogModule.Data/Repositories/CatalogRepositoryImpl.cs
> +        public virtual async Task<ProductConfigurationEntity> GetConfigurationByProductIdAsync(string productId, CancellationToken cancellationToken)
Can we just use GetConfigurationsByIdsAsync instead?

2024-11-22 11:23 UTC, ksavosteev commented on src/VirtoCommerce.CatalogModule.Data/Services/ProductConfigurationService.cs
> +    private void LoadDependencies(IList<ProductConfiguration> configurations)
rename to ResolveImageUrls

2024-11-22 12:22 UTC, Ljutyj commented on src/VirtoCommerce.CatalogModule.Data/Services/ProductConfigurationService.cs
> +    private void LoadDependencies(IList<ProductConfiguration> configurations)
Done

2024-11-22 14:19 UTC, ksavosteev approved these changes

2024-11-26 15:09 UTC, artem-dudarev approved these changes

2024-12-03 14:07 UTC, merged