VCST-2506: Export/Import  product configurations
VirtoCommerce/vc-module-catalog pull request #764
Opened 2024-12-26 11:04 UTC by Ljutyj

## Description
feat: Implemented the ability to export/import product configurations using Generic Export/Import

## References
### QA-test:
### Jira-link:
### Artifact URL:

2024-12-27 08:30 UTC, OlegoO approved these changes

2025-01-13 12:41 UTC, artem-dudarev requested changes

2025-01-13 12:41 UTC, artem-dudarev commented on src/VirtoCommerce.CatalogModule.Data/ExportImport2/ProductExportPagedDataSource.cs
> +                var searchResult = await _configurationSearchService.SearchNoCloneAsync(new ProductConfigurationSearchCriteria { ProductId = exportableProduct.Id });
Use AbstractTypeFactory when creating ProductConfigurationSearchCriteria.
Dont use SearchNoCloneAsync because this data source cannot guarantee that configurtion object will not be changed.
Try to reduce the number of calls to SearchAsync().

2025-01-13 12:41 UTC, artem-dudarev commented on src/VirtoCommerce.CatalogModule.Data/ExportImport/CatalogExportImport.cs
> +                    var searchResult = await _configurationSearchService.SearchNoCloneAsync(new ProductConfigurationSearchCriteria { Skip = skip, Take = take });
Use AbstractTypeFactory when creating ProductConfigurationSearchCriteria.
Dont use SearchNoCloneAsync because you are modifying found objects in ResetRedundantReferences()

2025-01-13 12:41 UTC, artem-dudarev commented on src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs
> +using VirtoCommerce.CatalogModule.Core.Model.Configuration;
Is this required?

2025-01-21 11:55 UTC, Ljutyj commented on src/VirtoCommerce.CatalogModule.Core/Model/CatalogProduct.cs
> +using VirtoCommerce.CatalogModule.Core.Model.Configuration;
No. It's an artifact). Fixed

2025-01-21 12:01 UTC, Ljutyj commented on src/VirtoCommerce.CatalogModule.Data/ExportImport/CatalogExportImport.cs
> +                    var searchResult = await _configurationSearchService.SearchNoCloneAsync(new ProductConfigurationSearchCriteria { Skip = skip, Take = take });
At the end of this code we receive serialized json string. It wouldn't be sent to  the DB and cache immediately. So I don't see any reason why we can't use the NoCloneAsync version in this case.

2025-01-30 09:19 UTC, merged